### ISSUE TITLE
SLP oracle should respect token decimals

### ISSUE THREAD

**Issue by johannbarbie** [sushiswap/bentobox#19]
i've tested the SLPTWAP oracle with different decimals. here is what i get:
```
collateral 1e21, asset 1e9 => oracle price 1e6
collateral 1e18, asset 1e9 => oracle price 1e9
collateral 1e18, asset 1e18 => oracle price 1e18
collateral 1e9, asset 1e18 => oracle price 1e27
```
it always giving the price for 1e18 of the ask currency, no matter what the decimals.

i expect the following values:
```
collateral 1e21, asset 1e9 => oracle price 1e9
collateral 1e18, asset 1e9 => oracle price 1e9
collateral 1e18, asset 1e18 => oracle price 1e18
collateral 1e9, asset 1e18 => oracle price 1e18
```
so giving the price for 1 full unit of the ask currency, considering the decimals. would make the implementation of `isSolvent()` and liquiditations more simple, imo.

**Comment by bartjman** [comment]
As discussed, it's perfect when it doesn't. The oracle should always return:

The number of collateral token units needed to buy 10^18 units of the asset token
