### ISSUE TITLE
support 1-tx deposit into LP

### ISSUE THREAD

**Issue by johannbarbie** [sushiswap/bentobox#27]
currently this is the only way to get into the Pair:

- `approve()` to Box, then `addAsset()`/`addCollateral()` to LP

which requires 2 transactions on the UI.

`addAssetWithPermit()` and `addCollateralWithPermit()` could forward receipts to Box. only useful for some tokens obviously.

**Comment by johannbarbie** [comment]
note, this this different than the permit in ERC20, which allows the Pair token to be deposited into other contracts.

**Comment by bartjman** [comment]
Yeah, feel free to add... I'm still not 100% happy with the ease of moving tokens in the BentoBox between clones. I think we probably need a router and the BentoBox needs transfer functions that take a permit. Not a token permit, but one specific to the BentoBox transfer functions.

**Comment by boringcrypto** [comment]
This has been resolved with batching/cooking.
