### ISSUE TITLE
Interface IPair defined twice

### ISSUE THREAD

**Issue by Clearwood** [sushiswap/bentobox#3]
The interface IPair is defined once in interfaces/IPair.sol (https://github.com/sushiswap/bentobox/blob/bb436ba65a425aa93ee5142801485877edf94edd/contracts/interfaces/IPair.sol#L6-L58) and again in Vault.sol (https://github.com/sushiswap/bentobox/blob/bb436ba65a425aa93ee5142801485877edf94edd/contracts/Vault.sol#L10-L12)

**Comment by bartjman** [comment]
Thanks, this has been fixed.
