### ISSUE TITLE
Publish compiled ABI's to NPM 

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/bentobox#36]
It would be great to include in the release pipeline publishing of ABI's to NPM to avoid the need for copying ABI's manually. I believe this already happens for https://github.com/sushiswap/sushiswap.

**Comment by boringcrypto** [comment]
Sounds good. Could you create a PR for this? Is this what LevX's PR does?

**Comment by matthewlilley** [comment]
@boringcrypto Yes, I just checked the PR and we can accept that, though I expect we'll need to increment version for the current state and republish.
