### ISSUE TITLE
Inclusion of a GPL3 library requires all code to become GPL3

### ISSUE THREAD

**Issue by dangerousfood** [sushiswap/bentobox#99]
GPL3 is infectious; any code that uses a GPL library automatically becomes GPL as well.

https://github.com/sushiswap/bentobox/blob/704aab1e5f151aadaff0b2fededd8a9a44e6362e/contracts/libraries/FixedPoint.sol#L1

**Comment by boringcrypto** [comment]
It's only used by "helper" contracts that are already MIT licensed (you can make them GPL if need be). These contracts are separate programs (not linked) to BentoBox and Kashi.
